### PR TITLE
Add a Chinese dict.

### PR DESCRIPTION
**Pull request by weakish**
It maps Pinyin to Chinese characters.

Related issue: #15

### CODE REVIEW

**Comment by koron** [comment]
@weakish I have one question.

You overwrote recent changes on config.mk.
Is it needed actually?

**Comment by koron** [comment]
Or just need translate comments?

**Comment by weakish** [comment]
> You overwrote recent changes on config.mk.

Sorry. I committed in the wrong version.

Repushed.

**Comment by koron** [comment]
thx!

**Pull request merged**
